writing_ideas = [
    "The clock struck midnight, and the door creaked open.",
    "She found a letter hidden under the floorboards.",
    "The rain never stopped in that strange little town.",
    "A shadow passed by the window, but no one was outside.",
    "The key to the mystery lay in an old, forgotten book.",
    "His reflection in the mirror wasn't his own.",
    "She woke up in a different time and place.",
    "The lighthouse beacon flickered before going out completely.",
    "He received a package with no return address.",
    "They never spoke of what happened that night.",
    "The old tree in the yard had a secret no one knew about.",
    "A stranger arrived in town with a dangerous secret.",
    "The painting on the wall seemed to change every day.",
    "The message appeared in the fog on the windowpane.",
    "An eerie silence fell over the city after the storm.",
    "He found a map that led to a place that didn't exist.",
    "The footsteps behind her stopped suddenly.",
    "A child’s voice whispered from behind the closed door.",
    "She discovered she could read minds, but only for a few seconds at a time.",
    "The moon was full, and something moved in the shadows.",
    "The diary entry ended abruptly, as if the writer was interrupted.",
    "The lights flickered, and when they came back on, he was gone.",
    "A strange mark appeared on her wrist overnight.",
    "She heard music, but no one else could.",
    "The cat stared at the empty corner of the room.",
    "A single rose was left on the doorstep every morning.",
    "He realized he was the only one who remembered the previous day.",
    "The fortune teller gave her a cryptic warning.",
    "They found a box buried in the backyard with no explanation.",
    "A forgotten friend from childhood appeared out of nowhere.",
    "The old radio crackled to life with a message from the past.",
    "Her dreams always came true, but in the worst way possible.",
    "He opened the book, and the words changed before his eyes.",
    "The elevator stopped on a floor that didn't exist.",
    "She was the only one who could see the figure in the fog.",
    "The town had a rule: no one was allowed to leave after dark.",
    "A picture on her phone showed something that wasn't there before.",
    "The more she tried to forget, the clearer the memory became.",
    "The note on the table wasn't in her handwriting.",
    "They found an old camera with undeveloped film.",
    "He woke up to find the world completely silent.",
    "The ocean seemed to whisper her name at night.",
    "A flickering streetlight always went out when she walked by.",
    "He received a phone call from someone who had been dead for years.",
    "She was trapped in the same moment, reliving it over and over.",
    "The wind carried voices no one else could hear.",
    "The map led them to a place that shouldn't have existed.",
    "He found a door in his house that he had never seen before.",
    "The clock on the wall was ticking backward.",
    "A message was scrawled on the wall in a language she didn't understand.",
    "Every night, the same dream ended at the same spot.",
    "They found a box filled with memories that weren't their own.",
    "The photograph was of her, but she had never been there before.",
    "He noticed that everyone around him was acting strangely.",
    "The letter was signed by someone she thought was long gone.",
    "They discovered a hidden room in the house that wasn't on the plans.",
    "A voice in her head kept telling her not to trust anyone.",
    "The clock tower rang thirteen times at midnight.",
    "An old friend returned, but they weren't the same person anymore.",
    "She saw a glimpse of the future and knew she had to stop it.",
    "They found a book that could predict the future.",
    "The house on the hill had been abandoned for years, or so they thought.",
    "He realized he could see people's auras, but they all looked wrong.",
    "The town was surrounded by a forest no one dared to enter.",
    "A melody only she could hear played whenever she was alone.",
    "A letter arrived, addressed to someone who had never lived there.",
    "The streetlamp outside flickered every night at the same time.",
    "He woke up with no memory of who he was.",
    "The sky turned a color no one had ever seen before.",
    "The mirror showed her something different from what she expected.",
    "He could hear whispers from the walls.",
    "She found a list of names, and hers was at the bottom.",
    "The river was said to take people to another world.",
    "The town's oldest resident claimed to be hundreds of years old.",
    "A book arrived at her door, but no one knew who sent it.",
    "The stars seemed to be moving in patterns she didn't recognize.",
    "He realized the painting on the wall was watching him.",
    "The candle flickered out, leaving her in total darkness.",
    "She woke up in a world where no one could see her.",
    "The room was filled with clocks, and none of them were on time.",
    "The old woman in town told them a story they couldn't believe.",
    "A tunnel appeared in the backyard overnight.",
    "The letter warned of a danger she couldn't understand.",
    "They found a book that could change the past.",
    "A man with no shadow walked past her on the street.",
    "The rain began, but the drops never touched the ground.",
    "He found a strange symbol carved into the tree.",
    "The news reported an event that hadn't happened yet.",
    "She started receiving text messages from her future self.",
    "The sand in the hourglass moved in the wrong direction.",
    "They found a door in the attic that led somewhere impossible.",
    "The watch on his wrist started ticking backward.",
    "She discovered a journal that detailed her future.",
    "The old piano played a haunting tune on its own.",
    "He realized he was the only one who could see the figure in the window.",
    "A mysterious package appeared on their doorstep every morning.",
    "The library contained books that weren't written yet.",
    "The world outside the window didn't look the same as it did yesterday.",
    "He woke up with a tattoo he didn't remember getting.",
    "The train station always had a train that went nowhere.",
    "They found a secret message hidden in a song.",
    "She saw her reflection, but it wasn't moving with her.",
    "The night sky was filled with unfamiliar stars.",
    "A knock on the door revealed no one outside, but a letter on the mat."
]